#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "../libs/catch.hpp"
#include "ArrayTests/array_tests.cpp"
#include "HeapTests/heap_tests.cpp"
#include "QueueTests/queue_tests.cpp"
#include "StackTests/stack_tests.cpp"
#include "LinkedListTests/unordered_linkedList_tests.cpp"
#include "LinkedListTests/ordered_linkedList_tests.cpp"
#include "GraphsTests/Incidence-Matrix/graph_tests.cpp"
#include "TreesTests/BstTests/bst_tests.cpp"
