version: 2
jobs:
  build:
    docker:
      - image: debian

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: "apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*"
      - run:
          name: Installing GCC
          command: "apt-get update && apt-get install -y gcc g++"
      - run:
          name: Install Pip
          command: "apt-get update && sudo apt-get install -y python3-pip"
      - run:
          name: Install CMAKE
          command: "pip3 install cmake==3.23.3"
      - run:
          name: Run unit tests application
          command: "chmod a+x buildRun.sh && ./buildRun.sh"
      - run:
          name: Print the Current Time
          command: date
